---
ID: "73e6c7d1-a9d0-44af-b88d-ca343a05295d"
Parent: "3683b1c1-1225-48d4-bc0b-28f0f73fd40c"
Template: "3683b1c1-1225-48d4-bc0b-28f0f73fd40c"
Path: /sitecore/templates/Foundation/blueyonder/Base Fields/_Primary Navigation/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240207T112257Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9046b54f-4cc7-43be-b727-b44df8f60177"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240207T112257Z
