---
ID: "46ce0422-f7ff-43a9-9ee7-ae673aa4c56f"
Parent: "8fdc1a9c-dc9d-4b04-a9c0-0a3abdede628"
Template: "8fdc1a9c-dc9d-4b04-a9c0-0a3abdede628"
Path: /sitecore/templates/Feature/blueyonder/Base Components/Footer/Footer Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {BE825819-E2EA-4E2D-A00F-75FFAAECA1C8}
    {8FDC1A9C-DC9D-4B04-A9C0-0A3ABDEDE628}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240207T114100Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "463c429e-39f7-4f55-b7f9-26618b573d10"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240207T114142Z
